import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "../globals.css";
import { ReduxProvider } from "@/app/providers";
import { GlobalAlert } from "@/shared/ui/alert";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Pizza | Оформление заказа",
  description: "Generated by create next app",
};

export default function OrderLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
      <main className="pt-10 h-full">
        <ReduxProvider>
          {children}
          {modal}
        </ReduxProvider>
      </main>
  );
}
